options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-instasafe', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-instasafe']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - spring-instasafe
      - --image=gcr.io/$PROJECT_ID/spring-instasafe
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080

images:
  - 'gcr.io/$PROJECT_ID/spring-instasafe'
